SET(3RDPARTY_ROOT ${PROJECT_SOURCE_DIR}/3rdparty)
SET(3RDPARTY_DIR ${PROJECT_SOURCE_DIR}/3rdparty/target/${TARGET_OS}_${TARGET_ARCH})
MESSAGE(STATUS "3RDPARTY_DIR: ${3RDPARTY_DIR}")

MACRO(LOAD_SPDLOG)
    ADD_DEFINITIONS(-DSPDLOG_USE_STD_FORMAT)
    FIND_PACKAGE(spdlog REQUIRED)
ENDMACRO()


MACRO(LOAD_GFLAGS)
    FIND_PACKAGE(gflags REQUIRED)
ENDMACRO()

MACRO(LOAD_GTEST)
    FIND_PACKAGE(GTest REQUIRED)
ENDMACRO()

MACRO(LOAD_GLOG)
    FIND_PACKAGE(glog REQUIRED)
ENDMACRO()
