name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CONAN_HOME: "${{ github.workspace }}/conan-home/.conan2"

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Print environment information
        run: |
          env
          uname -a

      - name: Install dependencies
        run: apt-get update && apt-get install -y build-essential cmake ninja-build pkg-config

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install Conan
        run: python -m pip install conan

      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: ${{ env.CONAN_HOME }}
          key: conan-${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('**/conanfile.*', 'conan.cmake') }}
          restore-keys: |
            conan-${{ runner.os }}-${{ matrix.build_type }}-

      - name: Configure with Conan and CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_INSTALL_PREFIX=install -G Ninja -DCMAKE_POLICY_DEFAULT_CMP0091=NEW

      - name: Build
        run: cmake --build build

      - name: Install
        working-directory: build
        run: cmake --install .

    strategy:
      matrix:
        build_type: [Release]
